services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RTfirst\PageGraph\:
    resource: '../Classes/*'

  dashboard.widget.pageGraph:
    class: RTfirst\PageGraph\Widgets\PageGraphWidget
    arguments:
      $options:
        includeContent: true
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'pageGraphWidget'
        groupNames: 'content'
        title: 'LLL:EXT:page_graph/Resources/Private/Language/locallang.xlf:widget.title'
        description: 'LLL:EXT:page_graph/Resources/Private/Language/locallang.xlf:widget.description'
        iconIdentifier: 'content-widget-chart'
        height: 'large'
        width: 'large'
